// Abertura --------------------------------------------------------------------------------------------------------------------------------------------------------------------
ALLEGRO_BITMAP *abertura0;
ALLEGRO_BITMAP *abertura1;
ALLEGRO_BITMAP *abertura2;
ALLEGRO_BITMAP *abertura3;
ALLEGRO_BITMAP *abertura4;
ALLEGRO_BITMAP *abertura5;
ALLEGRO_BITMAP *abertura6;
ALLEGRO_BITMAP *abertura7;
ALLEGRO_BITMAP *abertura8;
ALLEGRO_BITMAP *abertura9;
ALLEGRO_BITMAP *abertura10;
ALLEGRO_BITMAP *abertura11;
ALLEGRO_BITMAP *abertura12;
ALLEGRO_BITMAP *abertura13;
ALLEGRO_BITMAP *abertura14;
ALLEGRO_BITMAP *abertura15;
ALLEGRO_BITMAP *abertura16;
ALLEGRO_BITMAP *abertura17;
ALLEGRO_BITMAP *abertura18;
ALLEGRO_BITMAP *abertura19;
ALLEGRO_BITMAP *abertura20;
ALLEGRO_BITMAP *abertura21;
ALLEGRO_BITMAP *abertura22;
ALLEGRO_BITMAP *abertura23;
ALLEGRO_BITMAP *abertura24;
ALLEGRO_BITMAP *abertura25;
ALLEGRO_BITMAP *abertura26;
ALLEGRO_BITMAP *abertura27;
ALLEGRO_BITMAP *abertura28;
ALLEGRO_BITMAP *abertura29;
ALLEGRO_BITMAP *abertura30;
ALLEGRO_BITMAP *abertura31;
ALLEGRO_BITMAP *abertura32;
ALLEGRO_BITMAP *abertura33;
ALLEGRO_BITMAP *abertura34;
ALLEGRO_BITMAP *abertura35;
ALLEGRO_BITMAP *abertura36;
ALLEGRO_BITMAP *abertura37;
ALLEGRO_BITMAP *abertura38;
ALLEGRO_BITMAP *abertura39;
ALLEGRO_BITMAP *abertura40;
ALLEGRO_BITMAP *abertura41;
ALLEGRO_BITMAP *abertura42;
ALLEGRO_BITMAP *abertura43;
ALLEGRO_BITMAP *abertura44;
ALLEGRO_BITMAP *abertura45;
ALLEGRO_BITMAP *abertura46;
ALLEGRO_BITMAP *abertura47;
ALLEGRO_BITMAP *abertura48;
ALLEGRO_BITMAP *abertura49;
ALLEGRO_BITMAP *abertura50;
ALLEGRO_BITMAP *abertura51;
ALLEGRO_BITMAP *abertura52;
ALLEGRO_BITMAP *abertura53;
ALLEGRO_BITMAP *abertura54;
ALLEGRO_BITMAP *abertura55;
ALLEGRO_BITMAP *abertura56;
ALLEGRO_BITMAP *abertura57;
ALLEGRO_BITMAP *abertura58;
ALLEGRO_BITMAP *abertura59;
ALLEGRO_BITMAP *abertura60;
ALLEGRO_BITMAP *abertura61;
ALLEGRO_BITMAP *abertura62;
ALLEGRO_BITMAP *abertura63;
ALLEGRO_BITMAP *abertura64;
ALLEGRO_BITMAP *abertura65;
ALLEGRO_BITMAP *abertura66;
ALLEGRO_BITMAP *abertura67;
ALLEGRO_BITMAP *abertura68;
ALLEGRO_BITMAP *abertura69;
ALLEGRO_BITMAP *abertura70;
ALLEGRO_BITMAP *abertura71;
ALLEGRO_BITMAP *abertura72;
ALLEGRO_BITMAP *abertura73;
ALLEGRO_BITMAP *abertura74;
ALLEGRO_BITMAP *abertura75;
ALLEGRO_BITMAP *abertura76;
ALLEGRO_BITMAP *abertura77;
ALLEGRO_BITMAP *abertura78;
ALLEGRO_BITMAP *abertura79;
ALLEGRO_BITMAP *abertura80;
ALLEGRO_BITMAP *abertura81;
ALLEGRO_BITMAP *abertura82;
ALLEGRO_BITMAP *abertura83;
ALLEGRO_BITMAP *abertura84;
ALLEGRO_BITMAP *abertura85;
ALLEGRO_BITMAP *abertura86;
ALLEGRO_BITMAP *abertura87;
ALLEGRO_BITMAP *abertura88;
ALLEGRO_BITMAP *abertura89;
ALLEGRO_BITMAP *abertura90;
ALLEGRO_BITMAP *abertura91;

// Start --------------------------------------------------------------------------------------------------------------------------------------------------------------------
ALLEGRO_BITMAP *abertura92;
ALLEGRO_BITMAP *abertura93;
ALLEGRO_BITMAP *abertura94;
ALLEGRO_BITMAP *abertura95;
ALLEGRO_BITMAP *abertura96;
ALLEGRO_BITMAP *abertura97;
ALLEGRO_BITMAP *abertura98;
ALLEGRO_BITMAP *abertura99;
ALLEGRO_BITMAP *abertura100;

// Logo --------------------------------------------------------------------------------------------------------------------------------------------------------------------
ALLEGRO_BITMAP *logo;
ALLEGRO_BITMAP *by;

// Asteroide --------------------------------------------------------------------------------------------------------------------------------------------------------------------
ALLEGRO_BITMAP *asteroide0;
ALLEGRO_BITMAP *asteroide1;
ALLEGRO_BITMAP *asteroide2;
ALLEGRO_BITMAP *asteroide3;

// Background --------------------------------------------------------------------------------------------------------------------------------------------------------------------
ALLEGRO_BITMAP *background[40];
int frameBackground = 0;

// Tiro --------------------------------------------------------------------------------------------------------------------------------------------------------------------
ALLEGRO_BITMAP *tiro0;
ALLEGRO_BITMAP *tiro1;
ALLEGRO_BITMAP *tiro2;
ALLEGRO_BITMAP *tiro3;
ALLEGRO_BITMAP *tiro4;
ALLEGRO_BITMAP *tiro5;
ALLEGRO_BITMAP *tiro6;
ALLEGRO_BITMAP *tiro7;
ALLEGRO_BITMAP *tiro8;
ALLEGRO_BITMAP *TIRO0;
ALLEGRO_BITMAP *TIRO1;
ALLEGRO_BITMAP *TIRO2;
ALLEGRO_BITMAP *TIRO3;
ALLEGRO_BITMAP *TIRO4;
ALLEGRO_BITMAP *TIRO5;
ALLEGRO_BITMAP *TIRO6;
ALLEGRO_BITMAP *TIRO7;
ALLEGRO_BITMAP *TIRO8;
ALLEGRO_BITMAP *charge0;
ALLEGRO_BITMAP *charge1;
ALLEGRO_BITMAP *charge2;
ALLEGRO_BITMAP *charge3;
ALLEGRO_BITMAP *charge4;
ALLEGRO_BITMAP *charge5;
ALLEGRO_BITMAP *charge6;
ALLEGRO_BITMAP *charge7;
ALLEGRO_BITMAP *charge8;
ALLEGRO_BITMAP *charge9;
ALLEGRO_BITMAP *charge10;
ALLEGRO_BITMAP *charge11;
ALLEGRO_BITMAP *charge12;
ALLEGRO_BITMAP *charge13;
ALLEGRO_BITMAP *charge14;
ALLEGRO_BITMAP *charge15;
ALLEGRO_BITMAP *charge16;
ALLEGRO_BITMAP *charge17;
ALLEGRO_BITMAP *charge18;
ALLEGRO_BITMAP *CHARGE0;
ALLEGRO_BITMAP *CHARGE1;
ALLEGRO_BITMAP *CHARGE2;
ALLEGRO_BITMAP *CHARGE3;
ALLEGRO_BITMAP *CHARGE4;
ALLEGRO_BITMAP *CHARGE5;
ALLEGRO_BITMAP *CHARGE6;
ALLEGRO_BITMAP *CHARGE7;
ALLEGRO_BITMAP *CHARGE8;
ALLEGRO_BITMAP *CHARGE9;
ALLEGRO_BITMAP *CHARGE10;
ALLEGRO_BITMAP *CHARGE11;
ALLEGRO_BITMAP *CHARGE12;
ALLEGRO_BITMAP *CHARGE13;
ALLEGRO_BITMAP *CHARGE14;
ALLEGRO_BITMAP *CHARGE15;
ALLEGRO_BITMAP *CHARGE16;
ALLEGRO_BITMAP *CHARGE17;
ALLEGRO_BITMAP *CHARGE18;
ALLEGRO_BITMAP *CHARGE19;

// Nave --------------------------------------------------------------------------------------------------------------------------------------------------------------------
ALLEGRO_BITMAP *nave0;
ALLEGRO_BITMAP *nave2;
ALLEGRO_BITMAP *nave5;

// Inimigos --------------------------------------------------------------------------------------------------------------------------------------------------------------------
ALLEGRO_BITMAP *gemeos0;
ALLEGRO_BITMAP *gemeos1;
ALLEGRO_BITMAP *gemeos2;
ALLEGRO_BITMAP *gemeos3;
ALLEGRO_BITMAP *gemeos4;
ALLEGRO_BITMAP *gemeos5;
ALLEGRO_BITMAP *cobra0;
ALLEGRO_BITMAP *cobra1;
ALLEGRO_BITMAP *cobra2;
ALLEGRO_BITMAP *cobra3;
ALLEGRO_BITMAP *cobra4;
ALLEGRO_BITMAP *tiroinimigo0;

// Explosao --------------------------------------------------------------------------------------------------------------------------------------------------------------------
ALLEGRO_BITMAP *explosao0;
ALLEGRO_BITMAP *explosao1;
ALLEGRO_BITMAP *explosao2;
ALLEGRO_BITMAP *explosao3;
ALLEGRO_BITMAP *explosao4;
ALLEGRO_BITMAP *explosao5;
ALLEGRO_BITMAP *explosao6;

// Interface -------------------------------------------------------------------------------------------------------------------------------------------------------------
ALLEGRO_BITMAP *interface;
ALLEGRO_BITMAP *N1;
ALLEGRO_BITMAP *N2;
ALLEGRO_BITMAP *N3;
ALLEGRO_BITMAP *N4;
ALLEGRO_BITMAP *N5;
ALLEGRO_BITMAP *N6;
ALLEGRO_BITMAP *N7;
ALLEGRO_BITMAP *N8;
ALLEGRO_BITMAP *N9;
ALLEGRO_BITMAP *N0;
ALLEGRO_BITMAP *V1;
ALLEGRO_BITMAP *V2;
ALLEGRO_BITMAP *gameOver;
ALLEGRO_BITMAP *gameOver2;

void initBitmaps()
{
    // Asteroide --------------------------------------------------------------------------------------------------------------------------------------------------------------------
    abertura0 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-0.png");
    abertura1 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-1.png");
    abertura2 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-2.png");
    abertura3 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-3.png");
    abertura4 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-4.png");
    abertura5 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-5.png");
    abertura6 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-6.png");
    abertura7 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-7.png");
    abertura8 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-8.png");
    abertura9 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-9.png");
    abertura10 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-10.png");
    abertura11 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-11.png");
    abertura12 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-12.png");
    abertura13 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-13.png");
    abertura14 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-14.png");
    abertura15 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-15.png");
    abertura16 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-16.png");
    abertura17 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-17.png");
    abertura18 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-18.png");
    abertura19 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-19.png");
    abertura20 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-20.png");
    abertura21 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-21.png");
    abertura22 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-22.png");
    abertura23 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-23.png");
    abertura24 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-24.png");
    abertura25 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-25.png");
    abertura26 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-26.png");
    abertura27 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-27.png");
    abertura28 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-28.png");
    abertura29 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-28.png");
    abertura30 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-30.png");
    abertura31 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-31.png");
    abertura32 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-32.png");
    abertura33 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-33.png");
    abertura34 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-34.png");
    abertura35 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-35.png");
    abertura36 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-36.png");
    abertura37 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-37.png");
    abertura38 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-38.png");
    abertura39 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-39.png");
    abertura40 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-40.png");
    abertura41 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-41.png");
    abertura42 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-42.png");
    abertura43 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-43.png");
    abertura44 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-44.png");
    abertura45 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-45.png");
    abertura46 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-46.png");
    abertura47 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-47.png");
    abertura48 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-48.png");
    abertura49 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-49.png");
    abertura50 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-50.png");
    abertura51 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-51.png");
    abertura52 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-52.png");
    abertura53 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-53.png");
    abertura54 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-54.png");
    abertura55 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-55.png");
    abertura56 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-56.png");
    abertura57 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-57.png");
    abertura58 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-58.png");
    abertura59 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-59.png");
    abertura60 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-60.png");
    abertura61 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-61.png");
    abertura62 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-62.png");
    abertura63 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-63.png");
    abertura64 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-64.png");
    abertura65 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-65.png");
    abertura66 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-66.png");
    abertura67 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-67.png");
    abertura68 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-68.png");
    abertura69 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-69.png");
    abertura70 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-70.png");
    abertura71 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-71.png");
    abertura72 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-72.png");
    abertura73 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-73.png");
    abertura74 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-74.png");
    abertura75 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-75.png");
    abertura76 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-76.png");
    abertura77 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-77.png");
    abertura78 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-78.png");
    abertura79 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-79.png");
    abertura80 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-80.png");
    abertura81 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-81.png");
    abertura82 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-82.png");
    abertura83 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-83.png");
    abertura84 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-84.png");
    abertura85 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-85.png");
    abertura86 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-86.png");
    abertura87 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-87.png");
    abertura88 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-88.png");
    abertura89 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-89.png");
    abertura90 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-90.png");
    abertura91 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-91.png");

    // Start --------------------------------------------------------------------------------------------------------------------------------------------------------------------
    abertura92 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-92.png");
    abertura93 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-93.png");
    abertura94 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-94.png");
    abertura95 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-95.png");
    abertura96 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-96.png");
    abertura97 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-97.png");
    abertura98 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-98.png");
    abertura99 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-99.png");
    abertura100 = al_load_bitmap("src/sprites/Abertura/ezgif-3-70355ecc25-100.png");

    // Logo --------------------------------------------------------------------------------------------------------------------------------------------------------------------
    logo = al_load_bitmap("src/sprites/Abertura/logo.bmp");
    al_convert_mask_to_alpha(logo, al_map_rgb(0, 0, 0));
    by = al_load_bitmap("src/sprites/Abertura/by.png");
    al_convert_mask_to_alpha(by, al_map_rgb(255, 255, 255));

    // Asteroide --------------------------------------------------------------------------------------------------------------------------------------------------------------------
    asteroide0 = al_load_bitmap("src/sprites/Asteroide/asteroide0.png");
    al_convert_mask_to_alpha(asteroide0, al_map_rgb(255, 255, 255));
    asteroide1 = al_load_bitmap("src/sprites/Asteroide/asteroide1.png");
    al_convert_mask_to_alpha(asteroide1, al_map_rgb(255, 255, 255));
    asteroide2 = al_load_bitmap("src/sprites/Asteroide/asteroide2.png");
    al_convert_mask_to_alpha(asteroide2, al_map_rgb(255, 255, 255));
    asteroide3 = al_load_bitmap("src/sprites/Asteroide/asteroide3.png");
    al_convert_mask_to_alpha(asteroide3, al_map_rgb(255, 255, 255));

    // Asteroide --------------------------------------------------------------------------------------------------------------------------------------------------------------------
    background[0] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-0.png");
    background[1] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-1.png");
    background[2] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-2.png");
    background[3] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-3.png");
    background[4] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-4.png");
    background[5] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-5.png");
    background[6] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-6.png");
    background[7] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-7.png");
    background[8] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-8.png");
    background[9] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-9.png");
    background[10] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-10.png");
    background[11] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-11.png");
    background[12] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-12.png");
    background[13] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-13.png");
    background[14] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-14.png");
    background[15] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-15.png");
    background[16] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-16.png");
    background[17] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-17.png");
    background[18] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-18.png");
    background[19] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-19.png");
    background[20] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-20.png");
    background[21] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-21.png");
    background[22] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-22.png");
    background[23] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-23.png");
    background[24] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-24.png");
    background[25] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-25.png");
    background[26] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-26.png");
    background[27] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-27.png");
    background[28] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-28.png");
    background[29] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-29.png");
    background[30] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-30.png");
    background[31] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-31.png");
    background[32] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-32.png");
    background[33] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-33.png");
    background[34] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-34.png");
    background[35] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-35.png");
    background[36] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-36.png");
    background[37] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-37.png");
    background[38] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-38.png");
    background[39] = al_load_bitmap("src/sprites/Background/ezgif.com-gif-maker-39.png");

    // Tiro --------------------------------------------------------------------------------------------------------------------------------------------------------------------
    tiro0 = al_load_bitmap("src/sprites/Tiro/ezgif-3-4a53529086-0.png");
    al_convert_mask_to_alpha(tiro0, al_map_rgb(0, 0, 0));
    tiro1 = al_load_bitmap("src/sprites/Tiro/ezgif-3-4a53529086-1.png");
    al_convert_mask_to_alpha(tiro1, al_map_rgb(0, 0, 0));
    tiro2 = al_load_bitmap("src/sprites/Tiro/ezgif-3-4a53529086-2.png");
    al_convert_mask_to_alpha(tiro2, al_map_rgb(0, 0, 0));
    tiro3 = al_load_bitmap("src/sprites/Tiro/ezgif-3-4a53529086-3.png");
    al_convert_mask_to_alpha(tiro3, al_map_rgb(0, 0, 0));
    tiro4 = al_load_bitmap("src/sprites/Tiro/ezgif-3-4a53529086-4.png");
    al_convert_mask_to_alpha(tiro4, al_map_rgb(0, 0, 0));
    tiro5 = al_load_bitmap("src/sprites/Tiro/ezgif-3-4a53529086-5.png");
    al_convert_mask_to_alpha(tiro5, al_map_rgb(0, 0, 0));
    tiro6 = al_load_bitmap("src/sprites/Tiro/ezgif-3-4a53529086-6.png");
    al_convert_mask_to_alpha(tiro6, al_map_rgb(0, 0, 0));
    tiro7 = al_load_bitmap("src/sprites/Tiro/ezgif-3-4a53529086-7.png");
    al_convert_mask_to_alpha(tiro7, al_map_rgb(0, 0, 0));
    tiro8 = al_load_bitmap("src/sprites/Tiro/ezgif-3-4a53529086-8.png");
    al_convert_mask_to_alpha(tiro8, al_map_rgb(0, 0, 0));
    TIRO0 = al_load_bitmap("src/sprites/Tiro/TIRO0.png");
    al_convert_mask_to_alpha(TIRO0, al_map_rgb(0, 0, 0));
    TIRO1 = al_load_bitmap("src/sprites/Tiro/TIRO1.png");
    al_convert_mask_to_alpha(TIRO1, al_map_rgb(0, 0, 0));
    TIRO2 = al_load_bitmap("src/sprites/Tiro/TIRO2.png");
    al_convert_mask_to_alpha(TIRO2, al_map_rgb(0, 0, 0));
    TIRO3 = al_load_bitmap("src/sprites/Tiro/TIRO3.png");
    al_convert_mask_to_alpha(TIRO3, al_map_rgb(0, 0, 0));
    TIRO4 = al_load_bitmap("src/sprites/Tiro/TIRO4.png");
    al_convert_mask_to_alpha(TIRO4, al_map_rgb(0, 0, 0));
    TIRO5 = al_load_bitmap("src/sprites/Tiro/TIRO5.png");
    al_convert_mask_to_alpha(TIRO5, al_map_rgb(0, 0, 0));
    TIRO6 = al_load_bitmap("src/sprites/Tiro/TIRO6.png");
    al_convert_mask_to_alpha(TIRO6, al_map_rgb(0, 0, 0));
    TIRO7 = al_load_bitmap("src/sprites/Tiro/TIRO7.png");
    al_convert_mask_to_alpha(TIRO7, al_map_rgb(0, 0, 0));
    TIRO8 = al_load_bitmap("src/sprites/Tiro/TIRO8.png");
    al_convert_mask_to_alpha(TIRO8, al_map_rgb(0, 0, 0));
    charge0 = al_load_bitmap("src/sprites/Tiro/charge1-0.png");
    al_convert_mask_to_alpha(charge0, al_map_rgb(0, 0, 0));
    charge1 = al_load_bitmap("src/sprites/Tiro/charge1-1.png");
    al_convert_mask_to_alpha(charge1, al_map_rgb(0, 0, 0));
    charge2 = al_load_bitmap("src/sprites/Tiro/charge1-2.png");
    al_convert_mask_to_alpha(charge2, al_map_rgb(0, 0, 0));
    charge3 = al_load_bitmap("src/sprites/Tiro/charge1-3.png");
    al_convert_mask_to_alpha(charge3, al_map_rgb(0, 0, 0));
    charge4 = al_load_bitmap("src/sprites/Tiro/charge1-4.png");
    al_convert_mask_to_alpha(charge4, al_map_rgb(0, 0, 0));
    charge5 = al_load_bitmap("src/sprites/Tiro/charge1-5.png");
    al_convert_mask_to_alpha(charge5, al_map_rgb(0, 0, 0));
    charge6 = al_load_bitmap("src/sprites/Tiro/charge1-6.png");
    al_convert_mask_to_alpha(charge6, al_map_rgb(0, 0, 0));
    charge7 = al_load_bitmap("src/sprites/Tiro/charge1-7.png");
    al_convert_mask_to_alpha(charge7, al_map_rgb(0, 0, 0));
    charge8 = al_load_bitmap("src/sprites/Tiro/charge1-8.png");
    al_convert_mask_to_alpha(charge8, al_map_rgb(0, 0, 0));
    charge9 = al_load_bitmap("src/sprites/Tiro/charge1-9.png");
    al_convert_mask_to_alpha(charge9, al_map_rgb(0, 0, 0));
    charge10 = al_load_bitmap("src/sprites/Tiro/charge1-10.png");
    al_convert_mask_to_alpha(charge10, al_map_rgb(0, 0, 0));
    charge11 = al_load_bitmap("src/sprites/Tiro/charge1-11.png");
    al_convert_mask_to_alpha(charge11, al_map_rgb(0, 0, 0));
    charge12 = al_load_bitmap("src/sprites/Tiro/charge1-12.png");
    al_convert_mask_to_alpha(charge12, al_map_rgb(0, 0, 0));
    charge13 = al_load_bitmap("src/sprites/Tiro/charge1-13.png");
    al_convert_mask_to_alpha(charge13, al_map_rgb(0, 0, 0));
    charge14 = al_load_bitmap("src/sprites/Tiro/charge1-14.png");
    al_convert_mask_to_alpha(charge14, al_map_rgb(0, 0, 0));
    charge15 = al_load_bitmap("src/sprites/Tiro/charge1-15.png");
    al_convert_mask_to_alpha(charge15, al_map_rgb(0, 0, 0));
    charge16 = al_load_bitmap("src/sprites/Tiro/charge1-16.png");
    al_convert_mask_to_alpha(charge16, al_map_rgb(0, 0, 0));
    charge17 = al_load_bitmap("src/sprites/Tiro/charge1-17.png");
    al_convert_mask_to_alpha(charge17, al_map_rgb(0, 0, 0));
    charge18 = al_load_bitmap("src/sprites/Tiro/charge1-18.png");
    al_convert_mask_to_alpha(charge18, al_map_rgb(0, 0, 0));
    CHARGE0 = al_load_bitmap("src/sprites/Tiro/charge2-0.png");
    al_convert_mask_to_alpha(CHARGE0, al_map_rgb(0, 0, 0));
    CHARGE1 = al_load_bitmap("src/sprites/Tiro/charge2-1.png");
    al_convert_mask_to_alpha(CHARGE1, al_map_rgb(0, 0, 0));
    CHARGE2 = al_load_bitmap("src/sprites/Tiro/charge2-2.png");
    al_convert_mask_to_alpha(CHARGE2, al_map_rgb(0, 0, 0));
    CHARGE3 = al_load_bitmap("src/sprites/Tiro/charge2-3.png");
    al_convert_mask_to_alpha(CHARGE3, al_map_rgb(0, 0, 0));
    CHARGE4 = al_load_bitmap("src/sprites/Tiro/charge2-4.png");
    al_convert_mask_to_alpha(CHARGE4, al_map_rgb(0, 0, 0));
    CHARGE5 = al_load_bitmap("src/sprites/Tiro/charge2-5.png");
    al_convert_mask_to_alpha(CHARGE5, al_map_rgb(0, 0, 0));
    CHARGE6 = al_load_bitmap("src/sprites/Tiro/charge2-6.png");
    al_convert_mask_to_alpha(CHARGE6, al_map_rgb(0, 0, 0));
    CHARGE7 = al_load_bitmap("src/sprites/Tiro/charge2-7.png");
    al_convert_mask_to_alpha(CHARGE7, al_map_rgb(0, 0, 0));
    CHARGE8 = al_load_bitmap("src/sprites/Tiro/charge2-8.png");
    al_convert_mask_to_alpha(CHARGE8, al_map_rgb(0, 0, 0));
    CHARGE9 = al_load_bitmap("src/sprites/Tiro/charge2-9.png");
    al_convert_mask_to_alpha(CHARGE9, al_map_rgb(0, 0, 0));
    CHARGE10 = al_load_bitmap("src/sprites/Tiro/charge2-10.png");
    al_convert_mask_to_alpha(CHARGE10, al_map_rgb(0, 0, 0));
    CHARGE11 = al_load_bitmap("src/sprites/Tiro/charge2-11.png");
    al_convert_mask_to_alpha(CHARGE11, al_map_rgb(0, 0, 0));
    CHARGE12 = al_load_bitmap("src/sprites/Tiro/charge2-12.png");
    al_convert_mask_to_alpha(CHARGE12, al_map_rgb(0, 0, 0));
    CHARGE13 = al_load_bitmap("src/sprites/Tiro/charge2-13.png");
    al_convert_mask_to_alpha(CHARGE13, al_map_rgb(0, 0, 0));
    CHARGE14 = al_load_bitmap("src/sprites/Tiro/charge2-14.png");
    al_convert_mask_to_alpha(CHARGE14, al_map_rgb(0, 0, 0));
    CHARGE15 = al_load_bitmap("src/sprites/Tiro/charge2-15.png");
    al_convert_mask_to_alpha(CHARGE15, al_map_rgb(0, 0, 0));
    CHARGE16 = al_load_bitmap("src/sprites/Tiro/charge2-16.png");
    al_convert_mask_to_alpha(CHARGE16, al_map_rgb(0, 0, 0));
    CHARGE17 = al_load_bitmap("src/sprites/Tiro/charge2-17.png");
    al_convert_mask_to_alpha(CHARGE17, al_map_rgb(0, 0, 0));
    CHARGE18 = al_load_bitmap("src/sprites/Tiro/charge2-18.png");
    al_convert_mask_to_alpha(CHARGE18, al_map_rgb(0, 0, 0));
    CHARGE19 = al_load_bitmap("src/sprites/Tiro/charge2-19.png");
    al_convert_mask_to_alpha(CHARGE19, al_map_rgb(0, 0, 0));

    // Nave --------------------------------------------------------------------------------------------------------------------------------------------------------------------
    nave0 = al_load_bitmap("src/sprites/Nave/nave0.png");
    al_convert_mask_to_alpha(nave0, al_map_rgb(255, 255, 255));
    nave2 = al_load_bitmap("src/sprites/Nave/nave2.png");
    al_convert_mask_to_alpha(nave2, al_map_rgb(255, 255, 255));
    nave5 = al_load_bitmap("src/sprites/Nave/nave5.png");
    al_convert_mask_to_alpha(nave5, al_map_rgb(255, 255, 255));

    // Inimigos --------------------------------------------------------------------------------------------------------------------------------------------------------------------
    gemeos0 = al_load_bitmap("src/sprites/Inimigos/gemeos0.png");
    al_convert_mask_to_alpha(gemeos0, al_map_rgb(255, 255, 255));
    gemeos1 = al_load_bitmap("src/sprites/Inimigos/gemeos1.png");
    al_convert_mask_to_alpha(gemeos1, al_map_rgb(255, 255, 255));
    gemeos2 = al_load_bitmap("src/sprites/Inimigos/gemeos2.png");
    al_convert_mask_to_alpha(gemeos2, al_map_rgb(255, 255, 255));
    gemeos3 = al_load_bitmap("src/sprites/Inimigos/gemeos3.png");
    al_convert_mask_to_alpha(gemeos3, al_map_rgb(255, 255, 255));
    gemeos4 = al_load_bitmap("src/sprites/Inimigos/gemeos4.png");
    al_convert_mask_to_alpha(gemeos4, al_map_rgb(255, 255, 255));
    gemeos5 = al_load_bitmap("src/sprites/Inimigos/gemeos5.png");
    al_convert_mask_to_alpha(gemeos5, al_map_rgb(255, 255, 255));
    cobra0 = al_load_bitmap("src/sprites/Inimigos/cobra0.png");
    al_convert_mask_to_alpha(cobra0, al_map_rgb(255, 255, 255));
    cobra1 = al_load_bitmap("src/sprites/Inimigos/cobra1.png");
    al_convert_mask_to_alpha(cobra1, al_map_rgb(255, 255, 255));
    cobra2 = al_load_bitmap("src/sprites/Inimigos/cobra2.png");
    al_convert_mask_to_alpha(cobra2, al_map_rgb(255, 255, 255));
    cobra3 = al_load_bitmap("src/sprites/Inimigos/cobra3.png");
    al_convert_mask_to_alpha(cobra3, al_map_rgb(255, 255, 255));
    cobra4 = al_load_bitmap("src/sprites/Inimigos/cobra4.png");
    al_convert_mask_to_alpha(cobra4, al_map_rgb(255, 255, 255));
    tiroinimigo0 = al_load_bitmap("src/sprites/Inimigos/tiroinimigo0.png");
    al_convert_mask_to_alpha(tiroinimigo0, al_map_rgb(255, 255, 255));

    // Explosao --------------------------------------------------------------------------------------------------------------------------------------------------------------------
    explosao0 = al_load_bitmap("src/sprites/Explosao/ezgif-3-6d3dafe057-0.png");
    al_convert_mask_to_alpha(explosao0, al_map_rgb(0, 0, 0));
    explosao1 = al_load_bitmap("src/sprites/Explosao/ezgif-3-6d3dafe057-1.png");
    al_convert_mask_to_alpha(explosao1, al_map_rgb(0, 0, 0));
    explosao2 = al_load_bitmap("src/sprites/Explosao/ezgif-3-6d3dafe057-2.png");
    al_convert_mask_to_alpha(explosao2, al_map_rgb(0, 0, 0));
    explosao3 = al_load_bitmap("src/sprites/Explosao/ezgif-3-6d3dafe057-3.png");
    al_convert_mask_to_alpha(explosao3, al_map_rgb(0, 0, 0));
    explosao4 = al_load_bitmap("src/sprites/Explosao/ezgif-3-6d3dafe057-4.png");
    al_convert_mask_to_alpha(explosao4, al_map_rgb(0, 0, 0));
    explosao5 = al_load_bitmap("src/sprites/Explosao/ezgif-3-6d3dafe057-5.png");
    al_convert_mask_to_alpha(explosao5, al_map_rgb(0, 0, 0));
    explosao6 = al_load_bitmap("src/sprites/Explosao/ezgif-3-6d3dafe057-6.png");
    al_convert_mask_to_alpha(explosao6, al_map_rgb(0, 0, 0));

    // Interface --------------------------------------------------------------------------------------------------------------------------------------------------------------------
    interface = al_load_bitmap("src/sprites/Interface/interface.png");
    N1 = al_load_bitmap("src/sprites/Interface/N1.png");
    N2 = al_load_bitmap("src/sprites/Interface/N2.png");
    N3 = al_load_bitmap("src/sprites/Interface/N3.png");
    N4 = al_load_bitmap("src/sprites/Interface/N4.png");
    N5 = al_load_bitmap("src/sprites/Interface/N5.png");
    N6 = al_load_bitmap("src/sprites/Interface/N6.png");
    N7 = al_load_bitmap("src/sprites/Interface/N7.png");
    N8 = al_load_bitmap("src/sprites/Interface/N8.png");
    N9 = al_load_bitmap("src/sprites/Interface/N9.png");
    N0 = al_load_bitmap("src/sprites/Interface/N0.png");
    V1 = al_load_bitmap("src/sprites/Interface/V1.png");
    V2 = al_load_bitmap("src/sprites/Interface/V2.png");
    gameOver = al_load_bitmap("src/sprites/Interface/gameOver.png");
    al_convert_mask_to_alpha(gameOver, al_map_rgb(127, 127, 127));
    gameOver2 = al_load_bitmap("src/sprites/Interface/gameOver2.png");
    al_convert_mask_to_alpha(gameOver2, al_map_rgb(127, 127, 127));
}